server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: serie-service

spring:
    mongodb:
        embedded:
            version: 7.0.7
    data:
        mongodb:
            database: test
            port: 27017 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true