server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: serie-service
    
  zipkin:
    base-url: http://localhost:9411/
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0

  mongodb:
    embedded:
      version: 7.0.7
    data:
      mongodb:
        database: test
        port: 27017

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10